### ISSUE TITLE
mwc-drawer raises error when used from unpkg.com and cannot be used.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1096]
I would like to use the `mwc-drawer` and import the module from unpkg.com. But it fails with the error

```bash
Package blocking-elements@0.1.0 does not contain an ES module
```

![image](https://user-images.githubusercontent.com/42288570/78862109-d8a90680-7a36-11ea-93cf-0d18cc1e8606.png)

![image](https://user-images.githubusercontent.com/42288570/78862033-abf4ef00-7a36-11ea-98a6-33138125d3e3.png)

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Example App</title>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@next/webcomponents-loader.js"></script>
    <script type="module" src="https://unpkg.com/@material/mwc-drawer@0.14.1/mwc-drawer.js?module"></script>
    </head>
<body>
    Hello World
</body>
</html>
```

#### Additional Context

My use case for using the `mwc` components is described here https://github.com/material-components/material-components-web-components/issues/1080

Another user has experienced the same problem and reported it to unpkg.com https://github.com/mjackson/unpkg/issues/242#issuecomment-611327084

**Comment by e111077** [comment]
Hello, this seems to be because one of our dependencies, `blocking-elements`, is not published with a `module` flag in package.json. We are working to resolve this on that repo.

**Comment by e111077** [comment]
fixed

**Comment by MarcSkovMadsen** [comment]
Thanks. @e111077 . I can confirm the specific error. Unfortunately there are more and I still cannot load from unpkg.com. I've created a new bug report here https://github.com/material-components/material-components-web-components/issues/1105
