### ISSUE TITLE
Error when using unpkg: 'mwc-ripple' has already been defined as a custom element

### ISSUE THREAD

**Issue by salomvary** [material-components/material-components-web-components#1485]
**Describe the bug**

Following the recommendations [here](https://github.com/material-components/material-components-web-components/issues/1219#issuecomment-620290605) I am trying to use components without a build system with the help of unpkg.

**To Reproduce**
1. Go to https://jsbin.com/zeqahadusu/edit?html,console,output
2. Open the browser's Development Console
3. See error on the console, see `<mwc-button>` not rendered

**Expected behavior**
- No error should be logged
- Button should be rendered

**Browser Version:**
 - OS: macOS
 - Browser Chrome 83.0.4103.116, Firefox 77.0.1 

**Additional context**

The Network tab shows `@material/mwc-line-ripple` being loaded twice with two slightly different version specifiers causing the exception:

- `https://unpkg.com/@material/mwc-line-ripple@%5E0.16.1?module`
- `https://unpkg.com/@material/mwc-line-ripple@0.16.1?module`

I can not tell whether this is a bug/limitation of unpkg or the modules are published with transitive dependencies using the wrong version specifiers.

**Comment by e111077** [comment]
This should be fixed in the latest release. Can you please update your dependencies to v0.17.0 and try again?

**Comment by salomvary** [comment]
@e111077 Still getting `Uncaught DOMException: CustomElementRegistry.define: 'mwc-ripple' has already been defined as a custom element` with 0.17.2: https://jsbin.com/nekuriyohe/edit?html,console,output

**Comment by e111077** [comment]
can you please post the output of `npm ls @material/mwc-ripple`?

**Comment by salomvary** [comment]
@e111077 There is no npm involved in this story. See the original description or the link I posted previously.

**Comment by e111077** [comment]
This seems to be how JSbin handles redirects and running scripts. It seems when you define a specific file `.js` it will run it and its dependencies in the VM. When you import an unpkg package without calling the specific file, the unpkg redirects seem to run the files and dependencies as proper import calls not in the VM.

I can't tell what's going on exactly, buut it seems to all hinge on how JSbin is running scripts.

**Comment by e111077** [comment]
actually that last commment is wrong. It seems to be how chrome is running unpkg scripts in the VM when pointing to the file directly rather than the redirects from unpkg reading the `main` / `module` fields in `package.json`

**Comment by e111077** [comment]
Closing issue as we do not 100% support unpkg and unpkg related issues. We may be able to solve this in the future if we decide to pull list-item out into its own package
