### ISSUE TITLE
mwc-drawer: MDCDrawer:opened event fires twice

### ISSUE THREAD

**Issue by frankiefu** [material-components/material-components-web-components#220]
I added an event listener to mdc-drawer, e.g.
```
drawer.addEventListener('MDCDrawer:opened', (e) => {
  console.log('MDCDrawer:opened');
});
```

And when the drawer is opened `MDCDrawer:opened` is logged 2 times in the console.

**Comment by straversi** [comment]
It appears this was fixed by 9d51cc2224a1d0820944114ed3c54350ceba05f0, so thank you!

**Comment by frankiefu** [comment]
Nice. Yeah verified it's fixed.

**Comment by guther** [comment]
Here, the problem is still happened. I'm using "@material/drawer": "^12.0.0"
