### ISSUE TITLE
[mwc-checkbox] Ripple not visible when checkbox focused while unchecked

### ISSUE THREAD

**Issue by sorvell** [material-components/material-components-web-components#563]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**What OS are you using?**

Mac OS 10.14.6
**What browser(s) is this bug affecting:**

All
**Current behavior:**

When the checkbox is focused while it is unchecked, there is no focus indication.

**Expected behavior:**

When focused while being unchecked, the ripple should should in a focused state.

**Steps to reproduce:**

**Comment by aomarks** [comment]
Fixed by https://github.com/material-components/material-components-web-components/issues/515

**Comment by SpencerMcFadden** [comment]
As of 11/14/2019, version 0.10.0, this issue is still occurring
