### ISSUE TITLE
demos/index.html fail on Linux (Mint 18.3)

### ISSUE THREAD

**Issue by ShawnTalbert** [material-components/material-components-web-components#9]
After working around issue #8 by running `run npm bootstrap` with `/bin/bash` and it completing successfully, the demo site fails to display anything with the following error:

![image](https://user-images.githubusercontent.com/1332867/39675021-e0d5100e-5109-11e8-83c7-bc050e4ef04e.png)

Chrome Version 66.0.3359.139 (Official Build) (64-bit)

I tried `npm install @webcomponents/webcomponentsjs` but that didn't help the second error.

**Comment by azakus** [comment]
You have to use `http://127.0.0.1:8081/components/material-components-web-components/demos/index.html` for now

**Comment by azakus** [comment]
Should be fixed as of @8310a76180c8a74b5d88272c7de070e3dadaf74d

**Comment by ShawnTalbert** [comment]
unfortunately still doesn't work. Looks like this needs to mature a bit before I take another look. Good luck guys!
